### ISSUE TITLE
WOW! Is this really happening?

### ISSUE THREAD

**Issue by srameshr** [prscX/react-native-photo-editor#1]
Currently, devs are using https://github.com/npomfret/react-native-image-tools to integrate a decent photo editor. But, something like https://github.com/burhanrashid52/PhotoEditor would be amazing.

**Comment by prscX** [comment]
Thanks @srameshr for showing your interest. I am targeting 2-3 weeks for effort in order to have this in place.

Initially my goal was to integrate [burhanrashid52/PhotoEditor]( https://github.com/burhanrashid52/PhotoEditor) library but I could not find any similar library on iOS. As of now I was targeting below library to create a RN wrapper:

- [iOS: eventtus/photo-editor](https://github.com/eventtus/photo-editor)
- [Android: iOS: eventtus/photo-editor-android](https://github.com/eventtus/photo-editor-android)

Please let me know your view on the same.

Thanks
</ Pranav >

**Comment by srameshr** [comment]
Yes, **eventtus** editors look even better.
BTW, I have supported you via Buy Me A Coffee. Looking forward to this editor.

**Comment by prscX** [comment]
WOW! My very first Coffee 😄. Thanks for the support and interest.

I will keep you posted about the updates.

Thanks
</ Pranav >

**Comment by srameshr** [comment]
@prscX Also, do the original ios and android plugins support editing GIF's?

**Comment by prscX** [comment]
@srameshr: I doubt. I will explore the options of having GIF's editing support as well.

Will keep you posted.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @srameshr: Updates

Last weekend, I have integrated the native library on iOS, still few tunings are required. Coming weekend I am planning to work on the android part.

I will keep you posted about the updates.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @srameshr. I have integrated Android as well and it is working as expected.

Coming 2 days I am slightly lined-up with few other items. Coming Thursday I am planning to push the release targeting both Android & iOS.

Thanks
</ Pranav >

**Comment by prscX** [comment]
Hi @srameshr: As promised I have pushed the release for both Android & iOS.

Please follow `README` steps for the library setup, let me know incase you face any issues.

Thanks
</ Pranav >
