### ISSUE TITLE
Pods 

### ISSUE THREAD

**Issue by aurimas535** [prscX/react-native-photo-editor#20]
Is there are any way to install this lib without manually moving dependencies to iOs project folder? My project is using pods and usually is enough to run pod install. I tried there but that's not working, I got error that library is undefined. Any thought on this?

**Comment by prscX** [comment]
Thanks @aurimas535 for raising the query.

I completely agree with your concerns. Personally I have made multiple efforts in order to simplify the setup process but with no success. For time being this is the only setup process we have until someone shares a better way of doing the same.

P.S: This problem happens only when we try to integrate Swift library in Objective-C project.

Thanks
</ Pranav >
